#  docker compose file will link multiple containers together them together so they can communicate with each other
version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

